# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
